# Generated by Django 5.1.5 on 2025-02-03 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
